# Generated by Django 3.1.3 on 2020-11-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
